services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: dbserver
      WORDPRESS_DB_USER: vanjxdbuser
      WORDPRESS_DB_PASSWORD: vanjxdb123pwd
      WORDPRESS_DB_NAME: vanjxdbname
    volumes:
      - wordpress:/var/www/html

  dbserver:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vanjxdbname
      MYSQL_USER: vanjxdbuser
      MYSQL_PASSWORD: vanjxdb123pwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  wordpress:
  db:
